# Generated by Django 5.1.5 on 2025-03-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
