# Generated by Django 5.1.5 on 2025-03-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_shopuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
