# Generated by Django 5.1.5 on 2025-03-21 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_shopuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='address',
        ),
        migrations.AddField(
            model_name='shopuser',
            name='default_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_address', to='account.address'),
        ),
    ]
