# Generated by Django 5.1.5 on 2025-04-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_address_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.AlterModelOptions(
            name='shopuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر ها'},
        ),
    ]
