# Generated by Django 5.1.5 on 2025-03-30 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='shop.product'),
        ),
    ]
