# Generated by Django 5.1.5 on 2025-03-31 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_discountcode_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountcode',
            old_name='is_active',
            new_name='active',
        ),
    ]
