# Generated by Django 5.1.5 on 2025-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rename_is_active_discountcode_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='تخفیف'),
        ),
    ]
