# Generated by Django 5.1.5 on 2025-04-08 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_coupon_order_discount_amount_and_more'),
        ('shop', '0014_remove_discountcode_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.discountcode'),
        ),
    ]
