# Generated by Django 5.1.5 on 2025-04-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_discount_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount_code',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
