# Generated by Django 5.1.5 on 2025-04-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivery_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش ها'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'لیست سفارش', 'verbose_name_plural': 'لیست سفارش ها'},
        ),
    ]
