# Generated by Django 5.1.5 on 2025-04-12 18:15

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_address_address_alter_address_city_and_more'),
        ('orders', '0008_alter_order_options_alter_orderitem_options'),
        ('shop', '0015_alter_discountcode_options_alter_category_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.address', verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت آخر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'پرداخت آنلاین'), ('cod', 'پرداخت در محل'), ('bank', 'کارت به کارت')], default='online', max_length=20, verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='جمع قیمت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آپدیت شدن'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product', verbose_name='محصول'),
        ),
    ]
